require 'hoe'
require './lib/footballdb/leagues/version.rb'

Hoe.spec 'footballdb-leagues' do

  self.version = FootballDb::Leagues::VERSION

  self.summary = "footballdb-leagues - the world's top football leagues 'n' cups"
  self.description = summary

  self.urls = { home: 'https://github.com/sportdb/football.db' }

  self.author = 'Gerald Bauer'
  self.email = 'opensport@googlegroups.com'

  # switch extension to .markdown for gihub formatting
  self.readme_file  = 'README.md'
  self.history_file = 'CHANGELOG.md'

  self.licenses = ['Public Domain']

  self.extra_deps = [
    ['sportdb-formats',   '>= 1.1.2'],
    ['fifa',              '>= 2020.9.15'],
  ]

  self.spec_extras = {
    required_ruby_version: '>= 2.2.2'
  }

end
